### ISSUE TITLE
Can not stop a command after OS restart

### ISSUE THREAD

**Issue by Acris** [txthinking/joker#1]

**Comment by Acris** [comment]
It seems that joker saves the running information in the `/tmp/joker.list` file. The process has stopped after the system restarted, but the file content has not changed. As a result, the stopped processes will still be listed when the `joker list` command is executed. When using the `joker stop <pid>` command, the execution of the command will fail because the process no longer exists. Is it possible to optimize here?

**Comment by txthinking** [comment]
Many OS will clear /tmp when startup, looks like RedHat-like OS doesn't.
https://serverfault.com/questions/377348/when-does-tmp-get-cleared/377349

**Comment by Acris** [comment]
Thanks for the reply, I will manually delete it for now.

**Comment by txthinking** [comment]
Maybe joker can check pid first when print list

**Comment by txthinking** [comment]
v20200902
