### ISSUE TITLE
建议将 joker 与 jinbe 合二为一，实现开机自启动加守护进程，类似于 pm2, 但 pm2 用来做这个太重了

### ISSUE THREAD

**Issue by m2acgi** [txthinking/joker#10]
如题。谢谢。

**Comment by txthinking** [comment]
`nami install joker jinbe jb`, 小脚本可实现，保存到 `~/.nami/bin/jj`, `chmod +x ~/.nami/bin/jj`, 

```
#!/usr/bin/env jb

var cmd = process.argv.slice(3).map(v=>`"${v}"`).join(" ")
$(`joker ${cmd}`)
$(`jinbe joker ${cmd}`)
```

就可以
```
jj brook server --listen :9999 --password hello
```

**Comment by txthinking** [comment]
zhen v20231206

https://www.txthinking.com/talks/articles/zhen.article

https://www.txthinking.com/talks/articles/zhen-en.article
