### ISSUE TITLE
Could u kindly provide arm64 version ?

### ISSUE THREAD

**Issue by cutemanworking** [txthinking/joker#2]
Could u kindly provide arm64 version ?  Thanks in advanced!!!!

**Comment by txthinking** [comment]
It looks like we can use to cross compile https://github.com/dockcross/dockcross

**Comment by sinnerliu** [comment]
@cutemanworking 
You can try my compiled arm64
[joker_arm64.zip](https://github.com/txthinking/joker/files/5100967/joker_arm64.zip)

**Comment by sinnerliu** [comment]
I also modified it and compiled a version of windows with cygwin
[joker_windows_x64.zip](https://github.com/txthinking/joker/files/5100979/joker_windows_x64.zip)

**Comment by txthinking** [comment]
try v20200902
