### ISSUE TITLE
日志查看功能增强

### ISSUE THREAD

**Issue by cylind** [txthinking/joker#3]
开发者您好，我用joker有些时日了，joker小巧轻便，确实好用，但我今天遇到了一点点小问题，不知道怎么解决。
joker可以查看日志的，joker log pid，但是如果我的进程发生错误意外结束了，没有了pid了，我该怎么查看对应的日志呢？
我用 nohup cmd &时，日志文件是保存在当前文件夹下的nohup.out里，不知道joker 的日志是保存在哪里

**Comment by txthinking** [comment]
joker list -a 会显示包括停止的pid

**Comment by txthinking** [comment]
joker 写的文件 有 /tmp/joker.* 但不建议直接手动修改

**Comment by txthinking** [comment]
v20200902 $HOME/.joker/*
