### ISSUE TITLE
make遇错

### ISSUE THREAD

**Issue by briteming** [txthinking/joker#4]
git clone https://github.com/txthinking/joker joker-by-txthinking
cd joker-by-txthinking
make
显示：
gcc -Ilib -Wall -o list.o -c list.c
In file included from list.c:15:0:
joker.h:29:21: fatal error: sds/sds.h: No such file or directory
 #include "sds/sds.h"
                     ^
compilation terminated.
make: *** [list.o] Error 1

如何解决？

**Comment by txthinking** [comment]
https://github.com/txthinking/joker/blob/master/.gitmodules

**Comment by txthinking** [comment]
v20200902
