### ISSUE TITLE
Alpine Linux system cannot run

### ISSUE THREAD

**Issue by fejich** [txthinking/joker#5]
```
box:~$ ./joker 
-ash: ./joker: not found
```
What dependency is missing？

**Comment by txthinking** [comment]
$ ldd ./joker

it may be not work on Alpine, joker is not full static compile,
it requires built-in libc, and some built-in commands
https://github.com/txthinking/joker/blob/master/main.c#L54
https://github.com/txthinking/joker/blob/master/main.c#L84
